language: python
sudo: false

matrix:
  include:
    - python: '3.4'
      env: DJANGO2="django>=2.0,<2.1"
    - python: '3.5'
      env: DJANGO2="django>=2.0,<2.1"
    - python: '3.6'
      env: DJANGO2="django>=2.0,<2.1"

addons:
  apt:
    packages:
      - sqlite3
    sources:
      - travis-ci/sqlite3

branches:
  only:
    - master

# perform static analysis before installing all dependencies
# this allows to save resources and build time if this step fails
before_install:
  - pip install -U pip setuptools wheel
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort

# command to install requirements
install:
  - pip install $DJANGO2
  - python setup.py -q develop

# command to run tests, e.g. python setup.py test (test)
script:
  - coverage run --source=django_x509 runtests.py

after_success:
  coveralls
